# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
